"""Build the static site under docs/.

Reads:
  - latest blended events (today's slate) — generated by `cli build`
  - data/source_scoreboard.json — backtest output
  - data/source_weights.json — current weights

Writes:
  - docs/index.html (today's slate)
  - docs/event/<slug>.html
  - docs/source-scoreboard.html
  - docs/methodology.html
  - docs/backtest.html
  - docs/assets/flashcat-logo.svg + favicon.svg + favicon.png
  - docs/assets/bankroll.png + calibration.png
"""

from __future__ import annotations

import json
import logging
import math
import re
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .config import (
    ASSETS_DIR,
    DOCS_DIR,
    EVENT_PAGES_DIR,
    FLAT_STAKE,
    SOURCE_SCOREBOARD_PATH,
    SOURCE_WEIGHTS_PATH,
    bankroll,
    edge_threshold,
    ensure_dirs,
    stake_mode,
)
from .model.blend import _resolve_weights, load_weights
from .model.staking import StakeDecision, decide_stake
from .site.logo import cat_face_svg, write_favicon_png, write_logo
from .types import (
    BookLine,
    Event,
    SourceProb,
    american_to_prob,
    american_to_profit,
    devig_two_way,
)

STAKE_MODE_LABELS = {
    "flat": "flat",
    "kelly_quarter": "¼ Kelly",
    "kelly_half": "½ Kelly",
    "kelly_full": "full Kelly",
}

SKIP_REASON_LABELS = {
    "no_market_price": "No live price",
    "no_market_devig": "No two-way market",
    "within_no_bet_band": "Coin flip — no bet",
    "edge_below_threshold": "Edge below threshold — NO BET",
    "kelly_non_positive": "Kelly non-positive — NO BET",
    "degenerate_odds": "Degenerate odds",
}

log = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent / "site" / "templates"

BADGE_LABELS = {
    "chalk-overpriced": ("CHALK OVERPRICED", "chalk"),
    "reverse-line-movement-toward-home": ("RLM → HOME", "rlm"),
    "reverse-line-movement-toward-away": ("RLM → AWAY", "rlm"),
    "book-dispersion-dog": ("BOOK DISPERSION", "dispersion"),
}

SIGNAL_EXPLAIN = {
    "chalk-overpriced": "The market's implied probability on the favorite is materially higher than the model's. Books are charging a premium on the chalk — historically, the underdog has positive EV in these spots.",
    "reverse-line-movement-toward-home": "The home moneyline has moved toward home since open, often a sign sharp money is loaded on home regardless of where the public bets.",
    "reverse-line-movement-toward-away": "The home moneyline has moved away from home since open. Sharp money is on the road dog.",
    "book-dispersion-dog": "Books disagree by more than 4 percentage points on the underdog's implied probability. The soft books are out of step with the consensus.",
}


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html"]),
    )


def _slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "event"


def _research_mode_state(scoreboard: dict | None = None) -> dict:
    """Decide whether the site is LIVE BETTING or RESEARCH MODE.

    A site is in research mode when:
      * the blended backtest ROI is missing or non-positive overall, OR
      * ANY individual sport's blended ROI is negative.

    Phil's rule (2026-05-29): *"I am not putting any model on these games
    when the model backtest is -12%."* Until every sport we expose has a
    blended backtest ROI ≥ 0, the entire site is research-only.

    Returns dict with keys: ``research_mode`` (bool), ``roi`` (float|None),
    ``roi_str`` (str), and ``badge_label``/``badge_cls``.
    """
    if scoreboard is None:
        if SOURCE_SCOREBOARD_PATH.exists():
            try:
                with open(SOURCE_SCOREBOARD_PATH) as f:
                    scoreboard = json.load(f)
            except Exception:
                scoreboard = {}
        else:
            scoreboard = {}
    sources = (scoreboard or {}).get("sources", {}) if isinstance(scoreboard, dict) else {}
    fc = sources.get("flashcat-blended", {}) if isinstance(sources, dict) else {}
    blended_overall = (scoreboard or {}).get("blended_overall") if isinstance(scoreboard, dict) else None
    per_sport = (scoreboard or {}).get("per_sport") if isinstance(scoreboard, dict) else None
    roi = None
    if isinstance(blended_overall, dict) and blended_overall.get("roi") is not None:
        roi = blended_overall["roi"]
    elif isinstance(fc, dict) and fc.get("roi") is not None:
        roi = fc["roi"]

    # Aggregate research-mode triggers.
    research = False
    reason = None
    if roi is None:
        research, reason = True, "no backtest ROI available"
    elif roi <= 0:
        research, reason = True, f"overall ROI {roi*100:+.1f}%"
    elif isinstance(per_sport, dict):
        worst_sport = None
        worst_roi = None
        for sport, p in per_sport.items():
            bm = (p or {}).get("blended") or {}
            sport_roi = bm.get("roi")
            if sport_roi is None:
                continue
            if worst_roi is None or sport_roi < worst_roi:
                worst_roi = sport_roi
                worst_sport = sport
        if worst_roi is not None and worst_roi < 0:
            research, reason = True, f"{worst_sport.upper()} blended ROI {worst_roi*100:+.1f}%"

    roi_str = f"{roi*100:+.1f}%" if roi is not None else "n/a"
    if research:
        return {
            "research_mode": True,
            "roi": roi,
            "roi_str": roi_str,
            "reason": reason,
            "badge_label": "🟡 RESEARCH MODE",
            "badge_cls": "research",
        }
    return {
        "research_mode": False,
        "roi": roi,
        "roi_str": roi_str,
        "reason": None,
        "badge_label": "🟢 LIVE BETTING",
        "badge_cls": "live",
    }


def _layout(env: Environment, page_title: str, active: str, content_html: str, asset_root: str = "") -> str:
    layout = env.get_template("_layout.html")
    mode = stake_mode()
    rm = _research_mode_state()
    return layout.render(
        page_title=page_title,
        active=active,
        content=content_html,
        asset_root=asset_root,
        updated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        stake_mode_label=STAKE_MODE_LABELS.get(mode, mode),
        site_status_badge_label=rm["badge_label"],
        site_status_badge_cls=rm["badge_cls"],
        site_status_research=rm["research_mode"],
        site_status_roi_str=rm["roi_str"],
    )


def _market_devigged_home_prob(ev: Event) -> float | None:
    home_prices = [
        american_to_prob(ln.american) for ln in ev.lines if ln.side == "home" and not ln.is_opening
    ]
    away_prices = [
        american_to_prob(ln.american) for ln in ev.lines if ln.side == "away" and not ln.is_opening
    ]
    if not home_prices or not away_prices:
        return None
    h = sum(home_prices) / len(home_prices)
    a = sum(away_prices) / len(away_prices)
    h_devig, _ = devig_two_way(h, a)
    return h_devig


def _badge_blocks(signals: list[str]) -> list[dict]:
    out: list[dict] = []
    for sig in signals:
        if sig in BADGE_LABELS:
            label, cls = BADGE_LABELS[sig]
            out.append({"label": label, "cls": cls})
    return out


def _pick_price(ev: Event) -> int | None:
    if ev.pick is None:
        return None
    prices = [ln.american for ln in ev.lines if ln.side == ev.pick and not ln.is_opening]
    if not prices:
        prices = [ln.american for ln in ev.lines if ln.side == ev.pick]
    if not prices:
        return None
    return int(round(sum(prices) / len(prices)))


def _expected_profit_at_stake(price: int | None, win_prob: float | None, stake: float) -> float | None:
    if price is None or win_prob is None or stake <= 0:
        return None
    win_profit = american_to_profit(price, stake)
    return win_prob * win_profit - (1 - win_prob) * stake


def _stake_decision_for(ev: Event) -> StakeDecision | None:
    """Run the live staking decision for an event, if the model picked a side."""
    if ev.pick is None or ev.pick_prob is None:
        return None
    if not ev.lines:
        return None
    return decide_stake(
        ev,
        ev.pick,
        ev.pick_prob,
        mode=stake_mode(),
        bankroll=bankroll(),
        edge_threshold=edge_threshold(),
    )


def _event_view(ev: Event, weights: dict[str, float]) -> dict:
    market_p = _market_devigged_home_prob(ev)
    price = _pick_price(ev)
    badges = _badge_blocks(ev.signals)

    decision = _stake_decision_for(ev)
    bk = bankroll()
    mode_label = STAKE_MODE_LABELS.get(stake_mode(), stake_mode())
    threshold_pp = edge_threshold() * 100

    if decision is None:
        stake_value = 0.0
        edge_value: float | None = None
        edge_str = "—"
        edge_cls = ""
        recommended_stake_str = "NO BET — no market"
        ev_at_stake_str = "—"
        ev_at_stake: float | None = None
        is_recommended = False
    else:
        stake_value = float(decision.stake)
        edge_value = decision.edge
        edge_pp = decision.edge * 100
        edge_str = f"{edge_pp:+.1f} pp"
        edge_cls = "pos" if decision.edge > 0 else ("neg" if decision.edge < 0 else "")
        if stake_value > 0:
            pct = (stake_value / bk * 100) if bk > 0 else 0
            recommended_stake_str = (
                f"${stake_value:,.2f} ({mode_label}, {pct:.1f}% bankroll)"
            )
        else:
            reason = decision.skipped_reason or "edge_below_threshold"
            label = SKIP_REASON_LABELS.get(reason, "NO BET")
            if reason == "edge_below_threshold":
                label = f"NO BET — edge below {threshold_pp:.0f}pp"
            recommended_stake_str = label
        ev_at_stake = _expected_profit_at_stake(price, ev.pick_prob, stake_value) if stake_value > 0 else None
        ev_at_stake_str = f"${ev_at_stake:+,.2f}" if ev_at_stake is not None else "—"
        is_recommended = stake_value > 0

    return {
        "raw": ev,
        "slug": _slugify(f"{ev.commence_time.strftime('%Y-%m-%d')}-{ev.away}-at-{ev.home}-{ev.event_id[-6:]}"),
        "sport_upper": ev.sport.upper(),
        "sport": ev.sport,
        "commence_str": ev.commence_time.strftime("%a %b %d · %H:%M UTC"),
        "commence_iso": ev.commence_time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "n_sources": len(ev.source_probs),
        "pick_label": (ev.home if ev.pick == "home" else ev.away).upper() if ev.pick else "—",
        "pick_prob": ev.pick_prob or 0.0,
        "pick_price_str": _american_str(price) if price is not None else "—",
        "pick_price": price,
        "edge_value": edge_value,
        "edge_str": edge_str,
        "edge_cls": edge_cls,
        "recommended_stake": stake_value,
        "recommended_stake_str": recommended_stake_str,
        "ev_at_stake": ev_at_stake,
        "ev_at_stake_str": ev_at_stake_str,
        "is_recommended": is_recommended,
        "blended_home_prob": ev.blended_home_prob or 0.0,
        "market_home_str": f"{market_p:.1%}" if market_p is not None else "—",
        "badges": badges,
        "home": ev.home,
        "away": ev.away,
    }


def _american_str(price: int) -> str:
    return f"{price:+d}"


def _build_event_page_view(ev: Event, weights: dict[str, float]) -> dict:
    view = _event_view(ev, weights)
    src_names = [p.source for p in ev.source_probs]
    w_norm = _resolve_weights(src_names, weights) if src_names else {}
    source_rows = []
    for sp in ev.source_probs:
        source_rows.append(
            {
                "source": sp.source,
                "prob": sp.home_win_prob,
                "weight": w_norm.get(sp.source, 0.0),
                "captured": sp.captured_at.strftime("%Y-%m-%d %H:%M"),
            }
        )
    lines = []
    for ln in ev.lines:
        lines.append(
            {
                "book": ln.book,
                "side_label": ev.home if ln.side == "home" else ev.away,
                "american_str": _american_str(ln.american),
                "implied": american_to_prob(ln.american),
                "kind": "OPEN" if ln.is_opening else "CLOSE",
            }
        )
    signal_explanation = " ".join(
        SIGNAL_EXPLAIN.get(s, "") for s in ev.signals if s in SIGNAL_EXPLAIN
    )
    view.update({
        "source_rows": source_rows,
        "lines": lines,
        "signal_explanation": signal_explanation,
    })
    return view


def _write_logos() -> None:
    write_logo(ASSETS_DIR / "flashcat-logo.svg", with_text=False, size=256)
    write_logo(ASSETS_DIR / "favicon.svg", with_text=False, size=64)
    write_favicon_png(ASSETS_DIR / "favicon.png", size=64)


def _bankroll_chart(curve: list[dict], out_path: Path) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        log.warning("matplotlib not available; skipping bankroll chart")
        return
    if not curve:
        # write a stub chart with a "no data" note
        fig, ax = plt.subplots(figsize=(10, 4), facecolor="#1a1c22")
        ax.set_facecolor("#1a1c22")
        ax.text(0.5, 0.5, "No backtest data available", ha="center", va="center",
                fontsize=14, color="#8b8d96")
        ax.set_axis_off()
        fig.savefig(out_path, dpi=110, bbox_inches="tight", facecolor="#1a1c22")
        plt.close(fig)
        return
    xs = list(range(1, len(curve) + 1))
    ys = [pt["running_profit"] for pt in curve]
    fig, ax = plt.subplots(figsize=(10, 4), facecolor="#1a1c22")
    ax.set_facecolor("#1a1c22")
    color = "#F58220" if ys[-1] >= 0 else "#f87171"
    ax.plot(xs, ys, color=color, lw=2)
    ax.fill_between(xs, ys, 0, where=[y >= 0 for y in ys], color="#F58220", alpha=0.18)
    ax.fill_between(xs, ys, 0, where=[y < 0 for y in ys], color="#f87171", alpha=0.18)
    ax.axhline(0, color="#8b8d96", lw=0.8)
    ax.set_xlabel("Bet sequence", color="#8b8d96")
    ax.set_ylabel("Cumulative profit ($)", color="#8b8d96")
    ax.tick_params(colors="#8b8d96")
    for spine in ax.spines.values():
        spine.set_color("#2a2d36")
    ax.set_title("Flashcat blended model — bankroll curve", color="#f5f5f7", fontsize=13)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110, facecolor="#1a1c22")
    plt.close(fig)


def _calibration_chart(calibration: list[dict], out_path: Path) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return
    xs = [c["predicted"] for c in calibration if c.get("predicted") is not None]
    ys = [c["actual"] for c in calibration if c.get("actual") is not None]
    ns = [c["n"] for c in calibration if c.get("predicted") is not None]
    fig, ax = plt.subplots(figsize=(6, 5), facecolor="#1a1c22")
    ax.set_facecolor("#1a1c22")
    ax.plot([0, 1], [0, 1], color="#8b8d96", lw=0.8, ls="--")
    if xs:
        ax.scatter(xs, ys, s=[max(20, min(400, n * 4)) for n in ns],
                   color="#F58220", edgecolor="#1a1c22", linewidths=1.5, alpha=0.9)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Predicted probability", color="#8b8d96")
    ax.set_ylabel("Realized win rate", color="#8b8d96")
    ax.tick_params(colors="#8b8d96")
    for spine in ax.spines.values():
        spine.set_color("#2a2d36")
    ax.set_title("Flashcat calibration (10 bins)", color="#f5f5f7", fontsize=13)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110, facecolor="#1a1c22")
    plt.close(fig)


def render_index(env: Environment, events: list[Event], weights: dict[str, float]) -> str:
    # Render every live event, including those without a market line yet —
    # users want to see today's slate even when lines haven't published.
    rm = _research_mode_state()
    views = [_event_view(ev, weights) for ev in events]
    if rm["research_mode"]:
        # Suppress stake / EV / EDGE banner. Cards still render with sources
        # and the blended prob — Phil sees provenance, not stake recs.
        for v in views:
            v["is_recommended"] = False
            v["recommended_stake"] = 0.0
            v["recommended_stake_str"] = "Research only — backtest ROI not yet positive."
            v["ev_at_stake"] = None
            v["ev_at_stake_str"] = "—"
            v["edge_str"] = "—"
            v["edge_cls"] = ""
            v["edge_value"] = None
    # Pickable events are the subset where we'd actually place a bet.
    pickable = [v for v in views if v["pick_label"] != "—"]
    n_signals = sum(1 for v in pickable if v["badges"])
    n_chalk = sum(1 for v in pickable if any(b["cls"] == "chalk" for b in v["badges"]))

    # Top recommended plays: positive recommended stake, sorted by edge desc.
    # Suppressed entirely when in research mode.
    if rm["research_mode"]:
        recs = []
    else:
        recs = [v for v in views if v.get("is_recommended") and v.get("edge_value") is not None]
        recs.sort(key=lambda v: v["edge_value"], reverse=True)
    top_recs = recs[:5]
    total_recommended_stake = sum(v["recommended_stake"] for v in recs)
    mode_label = STAKE_MODE_LABELS.get(stake_mode(), stake_mode())

    content = env.get_template("index.html").render(
        events=views,
        n_events=len(views),
        n_pickable=len(pickable),
        n_recommended=len(recs),
        total_wagered=total_recommended_stake or len(pickable) * FLAT_STAKE,
        total_recommended_stake_str=f"${total_recommended_stake:,.2f}",
        n_signals=n_signals,
        n_chalk=n_chalk,
        top_recs=top_recs,
        stake_mode_label=mode_label,
        bankroll_str=f"${bankroll():,.0f}",
        edge_threshold_pp=f"{edge_threshold()*100:.1f}",
        research_mode=rm["research_mode"],
        backtest_roi_str=rm["roi_str"],
    )
    return _layout(env, "Today's Slate", "home", content, asset_root="")


def render_event_pages(env: Environment, events: list[Event], weights: dict[str, float]) -> None:
    template = env.get_template("event.html")
    ensure_dirs()
    for ev in events:
        # Render a page for every event — even ones we don't bet on, so the
        # slate-card click-throughs always resolve.
        view = _build_event_page_view(ev, weights)
        content = template.render(ev=view)
        full = _layout(env, f"{view['away']} @ {view['home']}", "home", content, asset_root="../")
        (EVENT_PAGES_DIR / f"{view['slug']}.html").write_text(full)


def render_sources(env: Environment, scoreboard: dict, weights: dict[str, float]) -> str:
    rows = []
    sources = scoreboard.get("sources", {}) if isinstance(scoreboard, dict) else {}
    if "flashcat-blended" in sources:
        keys = ["flashcat-blended"] + [k for k in sources if k != "flashcat-blended"]
    else:
        keys = list(sources.keys())
    for k in keys:
        v = sources[k]
        brier = v.get("brier")
        roi = v.get("roi")
        profit = v.get("profit")
        weight = weights.get(k, 0.0)
        rows.append({
            "source": k,
            "is_model": k == "flashcat-blended",
            "n_events": v.get("n_events", 0),
            "brier_str": f"{brier:.4f}" if brier is not None else "—",
            "roi_str": f"{roi:+.1%}" if roi is not None else "—",
            "roi_cls": ("pos" if (roi or 0) > 0 else "neg" if (roi or 0) < 0 else ""),
            "wl_str": f"{v.get('wins', 0)} / {v.get('losses', 0)}",
            "profit_str": f"${profit:+,.0f}" if profit is not None else "—",
            "profit_cls": ("pos" if (profit or 0) > 0 else "neg" if (profit or 0) < 0 else ""),
            "weight_str": f"{weight:.1%}" if weight else "—",
        })
    window_obj = scoreboard.get("window", {})
    window = f"{window_obj.get('start','—')} → {window_obj.get('end','—')}"
    content = env.get_template("sources.html").render(
        rows=rows,
        n_sources=len([r for r in rows if r["n_events"] > 0]),
        n_events=scoreboard.get("n_events", 0),
        window=window,
    )
    return _layout(env, "Source Scoreboard", "sources", content)


def render_methodology(env: Environment) -> str:
    content = env.get_template("methodology.html").render()
    return _layout(env, "Methodology", "methodology", content)


def render_backtest(env: Environment, scoreboard: dict) -> str:
    sources = scoreboard.get("sources", {})
    fc = sources.get("flashcat-blended", {})
    # Multi-sport scoreboards carry an overall blended block separately.
    blended_overall = scoreboard.get("blended_overall")
    if blended_overall:
        # The blended_overall block is the bottom line when running multi-sport.
        # Keep fc's calibration if present, but overwrite the headline numbers.
        for k in ("n_events", "wagered", "profit", "roi", "wins", "losses"):
            if blended_overall.get(k) is not None:
                fc[k] = blended_overall[k]
    slices_raw = fc.get("slices", {}) or {}
    slice_rows = []
    for label, v in sorted(slices_raw.items()):
        wagered = v.get("wagered", 0.0)
        profit = v.get("profit", 0.0)
        wins = int(v.get("wins", 0))
        losses = int(v.get("losses", 0))
        n = wins + losses
        roi = v.get("roi")
        slice_rows.append({
            "label": label,
            "n": n,
            "wl": f"{wins} / {losses}",
            "wagered": wagered,
            "profit_str": f"${profit:+,.0f}",
            "profit_cls": "pos" if profit > 0 else "neg" if profit < 0 else "",
            "roi_str": f"{roi:+.1%}" if roi is not None else "—",
            "roi_cls": "pos" if (roi or 0) > 0 else "neg" if (roi or 0) < 0 else "",
        })
    overall_roi = fc.get("roi")
    overall_brier = fc.get("brier")
    overall_profit = fc.get("profit", 0.0)
    window_obj = scoreboard.get("window", {})
    window = f"{window_obj.get('start','—')} → {window_obj.get('end','—')}"
    # Render charts
    _bankroll_chart(scoreboard.get("bankroll_curve", []) or [], ASSETS_DIR / "bankroll.png")
    _calibration_chart(fc.get("calibration", []) or [], ASSETS_DIR / "calibration.png")
    # Per-sport rows for the multi-sport breakdown table.
    per_sport_rows = []
    for sport, p in (scoreboard.get("per_sport") or {}).items():
        bm = p.get("blended") or {}
        if not bm:
            per_sport_rows.append({
                "sport": sport.upper(),
                "n": p.get("n_events", 0),
                "bets": 0,
                "wagered_str": "—",
                "profit_str": "—",
                "roi_str": "—",
                "roi_cls": "",
                "brier_str": "—",
            })
            continue
        roi = bm.get("roi")
        per_sport_rows.append({
            "sport": sport.upper(),
            "n": bm.get("n_events", 0),
            "bets": (bm.get("wins", 0) + bm.get("losses", 0)),
            "wagered_str": f"${bm.get('wagered', 0):,.0f}",
            "profit_str": f"${bm.get('profit', 0):+,.0f}",
            "roi_str": f"{roi:+.2%}" if roi is not None else "—",
            "roi_cls": "pos" if (roi or 0) > 0 else "neg" if (roi or 0) < 0 else "",
            "brier_str": f"{bm.get('brier', 0):.4f}" if bm.get("brier") is not None else "—",
        })
    content = env.get_template("backtest.html").render(
        window=window,
        n_events=fc.get("n_events", 0),
        overall_roi_str=f"{overall_roi:+.1%}" if overall_roi is not None else "—",
        overall_roi_cls="pos" if (overall_roi or 0) > 0 else "neg" if (overall_roi or 0) < 0 else "",
        overall_brier_str=f"{overall_brier:.4f}" if overall_brier is not None else "—",
        overall_profit_str=f"${overall_profit:+,.0f}",
        overall_profit_cls="pos" if overall_profit > 0 else "neg" if overall_profit < 0 else "",
        slice_rows=slice_rows,
        per_sport_rows=per_sport_rows,
        stake_mode=scoreboard.get("stake_mode", "flat"),
        edge_threshold=scoreboard.get("edge_threshold", 0.0),
    )
    return _layout(env, "Backtest", "backtest", content)


def write_source_scoreboard_md(scoreboard: dict, path: Path) -> None:
    sources = scoreboard.get("sources", {})
    lines = ["# Source Scoreboard\n"]
    window = scoreboard.get("window", {})
    lines.append(f"Window: **{window.get('start','—')} → {window.get('end','—')}** ({window.get('sport','—')})\n")
    lines.append(f"Events graded: **{scoreboard.get('n_events', 0)}**\n\n")
    lines.append("| Source | Events | Brier ↓ | ROI | Wins/Losses | Profit |\n")
    lines.append("|---|---:|---:|---:|---:|---:|\n")
    for src, v in sources.items():
        brier = v.get("brier")
        roi = v.get("roi")
        profit = v.get("profit")
        lines.append(
            f"| {src} | {v.get('n_events',0)} | "
            f"{brier:.4f}" if brier is not None else f"| {src} | {v.get('n_events',0)} | — "
        )
        # Simpler implementation: just rebuild line cleanly.
    # rebuild cleanly
    lines = ["# Source Scoreboard\n"]
    lines.append(f"Window: **{window.get('start','—')} → {window.get('end','—')}** ({window.get('sport','—')})\n\n")
    lines.append(f"Events graded: **{scoreboard.get('n_events', 0)}**\n\n")
    lines.append("| Source | Events | Brier ↓ | ROI | Wins/Losses | Profit |\n")
    lines.append("|---|---:|---:|---:|---:|---:|\n")
    for src, v in sources.items():
        brier = v.get("brier")
        roi = v.get("roi")
        profit = v.get("profit")
        brier_s = f"{brier:.4f}" if brier is not None else "—"
        roi_s = f"{roi:+.1%}" if roi is not None else "—"
        profit_s = f"${profit:+,.0f}" if profit is not None else "—"
        lines.append(
            f"| {src} | {v.get('n_events',0)} | {brier_s} | {roi_s} | "
            f"{v.get('wins',0)}/{v.get('losses',0)} | {profit_s} |\n"
        )
    path.write_text("".join(lines))


def build(events: list[Event] | None = None) -> None:
    ensure_dirs()
    _write_logos()
    weights = load_weights()
    if SOURCE_SCOREBOARD_PATH.exists():
        with open(SOURCE_SCOREBOARD_PATH) as f:
            scoreboard = json.load(f)
    else:
        scoreboard = {"sources": {}, "n_events": 0, "window": {}, "bankroll_curve": []}
    events = events or []
    env = _env()
    (DOCS_DIR / "index.html").write_text(render_index(env, events, weights))
    render_event_pages(env, events, weights)
    (DOCS_DIR / "source-scoreboard.html").write_text(render_sources(env, scoreboard, weights))
    (DOCS_DIR / "methodology.html").write_text(render_methodology(env))
    (DOCS_DIR / "backtest.html").write_text(render_backtest(env, scoreboard))
    write_source_scoreboard_md(scoreboard, DOCS_DIR / "source-scoreboard.md")
    log.info("Site built → %s", DOCS_DIR)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    build()
