"""Build the static site under docs/.

Reads:
  - latest blended events (today's slate) — generated by `cli build`
  - data/source_scoreboard.json — backtest output
  - data/source_weights.json — current weights

Writes:
  - docs/index.html (today's slate)
  - docs/event/<slug>.html
  - docs/source-scoreboard.html
  - docs/methodology.html
  - docs/backtest.html
  - docs/assets/flashcat-logo.svg + favicon.svg + favicon.png
  - docs/assets/bankroll.png + calibration.png
"""

from __future__ import annotations

import json
import logging
import math
import re
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .config import (
    ASSETS_DIR,
    DOCS_DIR,
    EVENT_PAGES_DIR,
    FLAT_STAKE,
    SOURCE_SCOREBOARD_PATH,
    SOURCE_WEIGHTS_PATH,
    ensure_dirs,
)
from .model.blend import _resolve_weights, load_weights
from .site.logo import cat_face_svg, write_favicon_png, write_logo
from .types import (
    BookLine,
    Event,
    SourceProb,
    american_to_prob,
    american_to_profit,
    devig_two_way,
)

log = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent / "site" / "templates"

BADGE_LABELS = {
    "chalk-overpriced": ("CHALK OVERPRICED", "chalk"),
    "reverse-line-movement-toward-home": ("RLM → HOME", "rlm"),
    "reverse-line-movement-toward-away": ("RLM → AWAY", "rlm"),
    "book-dispersion-dog": ("BOOK DISPERSION", "dispersion"),
}

SIGNAL_EXPLAIN = {
    "chalk-overpriced": "The market's implied probability on the favorite is materially higher than the model's. Books are charging a premium on the chalk — historically, the underdog has positive EV in these spots.",
    "reverse-line-movement-toward-home": "The home moneyline has moved toward home since open, often a sign sharp money is loaded on home regardless of where the public bets.",
    "reverse-line-movement-toward-away": "The home moneyline has moved away from home since open. Sharp money is on the road dog.",
    "book-dispersion-dog": "Books disagree by more than 4 percentage points on the underdog's implied probability. The soft books are out of step with the consensus.",
}


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html"]),
    )


def _slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "event"


def _layout(env: Environment, page_title: str, active: str, content_html: str, asset_root: str = "") -> str:
    layout = env.get_template("_layout.html")
    return layout.render(
        page_title=page_title,
        active=active,
        content=content_html,
        asset_root=asset_root,
        updated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )


def _market_devigged_home_prob(ev: Event) -> float | None:
    home_prices = [
        american_to_prob(ln.american) for ln in ev.lines if ln.side == "home" and not ln.is_opening
    ]
    away_prices = [
        american_to_prob(ln.american) for ln in ev.lines if ln.side == "away" and not ln.is_opening
    ]
    if not home_prices or not away_prices:
        return None
    h = sum(home_prices) / len(home_prices)
    a = sum(away_prices) / len(away_prices)
    h_devig, _ = devig_two_way(h, a)
    return h_devig


def _badge_blocks(signals: list[str]) -> list[dict]:
    out: list[dict] = []
    for sig in signals:
        if sig in BADGE_LABELS:
            label, cls = BADGE_LABELS[sig]
            out.append({"label": label, "cls": cls})
    return out


def _pick_price(ev: Event) -> int | None:
    if ev.pick is None:
        return None
    prices = [ln.american for ln in ev.lines if ln.side == ev.pick and not ln.is_opening]
    if not prices:
        prices = [ln.american for ln in ev.lines if ln.side == ev.pick]
    if not prices:
        return None
    return int(round(sum(prices) / len(prices)))


def _expected_profit(ev: Event, price: int | None) -> float | None:
    if price is None or ev.pick_prob is None:
        return None
    win_profit = american_to_profit(price, FLAT_STAKE)
    return ev.pick_prob * win_profit - (1 - ev.pick_prob) * FLAT_STAKE


def _event_view(ev: Event, weights: dict[str, float]) -> dict:
    market_p = _market_devigged_home_prob(ev)
    price = _pick_price(ev)
    ep = _expected_profit(ev, price)
    badges = _badge_blocks(ev.signals)
    return {
        "raw": ev,
        "slug": _slugify(f"{ev.commence_time.strftime('%Y-%m-%d')}-{ev.away}-at-{ev.home}-{ev.event_id[-6:]}"),
        "sport_upper": ev.sport.upper(),
        "commence_str": ev.commence_time.strftime("%a %b %d · %H:%M UTC"),
        "n_sources": len(ev.source_probs),
        "pick_label": (ev.home if ev.pick == "home" else ev.away).upper() if ev.pick else "—",
        "pick_prob": ev.pick_prob or 0.0,
        "pick_price_str": _american_str(price) if price is not None else "—",
        "expected_profit": ep,
        "expected_profit_str": f"${ep:+.0f}" if ep is not None else "—",
        "blended_home_prob": ev.blended_home_prob or 0.0,
        "market_home_str": f"{market_p:.1%}" if market_p is not None else "—",
        "badges": badges,
        "home": ev.home,
        "away": ev.away,
    }


def _american_str(price: int) -> str:
    return f"{price:+d}"


def _build_event_page_view(ev: Event, weights: dict[str, float]) -> dict:
    view = _event_view(ev, weights)
    src_names = [p.source for p in ev.source_probs]
    w_norm = _resolve_weights(src_names, weights) if src_names else {}
    source_rows = []
    for sp in ev.source_probs:
        source_rows.append(
            {
                "source": sp.source,
                "prob": sp.home_win_prob,
                "weight": w_norm.get(sp.source, 0.0),
                "captured": sp.captured_at.strftime("%Y-%m-%d %H:%M"),
            }
        )
    lines = []
    for ln in ev.lines:
        lines.append(
            {
                "book": ln.book,
                "side_label": ev.home if ln.side == "home" else ev.away,
                "american_str": _american_str(ln.american),
                "implied": american_to_prob(ln.american),
                "kind": "OPEN" if ln.is_opening else "CLOSE",
            }
        )
    signal_explanation = " ".join(
        SIGNAL_EXPLAIN.get(s, "") for s in ev.signals if s in SIGNAL_EXPLAIN
    )
    view.update({
        "source_rows": source_rows,
        "lines": lines,
        "signal_explanation": signal_explanation,
    })
    return view


def _write_logos() -> None:
    write_logo(ASSETS_DIR / "flashcat-logo.svg", with_text=False, size=256)
    write_logo(ASSETS_DIR / "favicon.svg", with_text=False, size=64)
    write_favicon_png(ASSETS_DIR / "favicon.png", size=64)


def _bankroll_chart(curve: list[dict], out_path: Path) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        log.warning("matplotlib not available; skipping bankroll chart")
        return
    if not curve:
        # write a stub chart with a "no data" note
        fig, ax = plt.subplots(figsize=(10, 4), facecolor="#1a1c22")
        ax.set_facecolor("#1a1c22")
        ax.text(0.5, 0.5, "No backtest data available", ha="center", va="center",
                fontsize=14, color="#8b8d96")
        ax.set_axis_off()
        fig.savefig(out_path, dpi=110, bbox_inches="tight", facecolor="#1a1c22")
        plt.close(fig)
        return
    xs = list(range(1, len(curve) + 1))
    ys = [pt["running_profit"] for pt in curve]
    fig, ax = plt.subplots(figsize=(10, 4), facecolor="#1a1c22")
    ax.set_facecolor("#1a1c22")
    color = "#F58220" if ys[-1] >= 0 else "#f87171"
    ax.plot(xs, ys, color=color, lw=2)
    ax.fill_between(xs, ys, 0, where=[y >= 0 for y in ys], color="#F58220", alpha=0.18)
    ax.fill_between(xs, ys, 0, where=[y < 0 for y in ys], color="#f87171", alpha=0.18)
    ax.axhline(0, color="#8b8d96", lw=0.8)
    ax.set_xlabel("Bet sequence", color="#8b8d96")
    ax.set_ylabel("Cumulative profit ($)", color="#8b8d96")
    ax.tick_params(colors="#8b8d96")
    for spine in ax.spines.values():
        spine.set_color("#2a2d36")
    ax.set_title("Flashcat blended model — bankroll curve", color="#f5f5f7", fontsize=13)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110, facecolor="#1a1c22")
    plt.close(fig)


def _calibration_chart(calibration: list[dict], out_path: Path) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return
    xs = [c["predicted"] for c in calibration if c.get("predicted") is not None]
    ys = [c["actual"] for c in calibration if c.get("actual") is not None]
    ns = [c["n"] for c in calibration if c.get("predicted") is not None]
    fig, ax = plt.subplots(figsize=(6, 5), facecolor="#1a1c22")
    ax.set_facecolor("#1a1c22")
    ax.plot([0, 1], [0, 1], color="#8b8d96", lw=0.8, ls="--")
    if xs:
        ax.scatter(xs, ys, s=[max(20, min(400, n * 4)) for n in ns],
                   color="#F58220", edgecolor="#1a1c22", linewidths=1.5, alpha=0.9)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Predicted probability", color="#8b8d96")
    ax.set_ylabel("Realized win rate", color="#8b8d96")
    ax.tick_params(colors="#8b8d96")
    for spine in ax.spines.values():
        spine.set_color("#2a2d36")
    ax.set_title("Flashcat calibration (10 bins)", color="#f5f5f7", fontsize=13)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110, facecolor="#1a1c22")
    plt.close(fig)


def render_index(env: Environment, events: list[Event], weights: dict[str, float]) -> str:
    views = [_event_view(ev, weights) for ev in events if ev.pick is not None]
    n_signals = sum(1 for v in views if v["badges"])
    n_chalk = sum(1 for v in views if any(b["cls"] == "chalk" for b in v["badges"]))
    content = env.get_template("index.html").render(
        events=views,
        n_events=len(views),
        total_wagered=len(views) * FLAT_STAKE,
        n_signals=n_signals,
        n_chalk=n_chalk,
    )
    return _layout(env, "Today's Slate", "home", content, asset_root="")


def render_event_pages(env: Environment, events: list[Event], weights: dict[str, float]) -> None:
    template = env.get_template("event.html")
    ensure_dirs()
    for ev in events:
        if ev.pick is None:
            continue
        view = _build_event_page_view(ev, weights)
        content = template.render(ev=view)
        full = _layout(env, f"{view['away']} @ {view['home']}", "home", content, asset_root="../")
        (EVENT_PAGES_DIR / f"{view['slug']}.html").write_text(full)


def render_sources(env: Environment, scoreboard: dict, weights: dict[str, float]) -> str:
    rows = []
    sources = scoreboard.get("sources", {}) if isinstance(scoreboard, dict) else {}
    if "flashcat-blended" in sources:
        keys = ["flashcat-blended"] + [k for k in sources if k != "flashcat-blended"]
    else:
        keys = list(sources.keys())
    for k in keys:
        v = sources[k]
        brier = v.get("brier")
        roi = v.get("roi")
        profit = v.get("profit")
        weight = weights.get(k, 0.0)
        rows.append({
            "source": k,
            "is_model": k == "flashcat-blended",
            "n_events": v.get("n_events", 0),
            "brier_str": f"{brier:.4f}" if brier is not None else "—",
            "roi_str": f"{roi:+.1%}" if roi is not None else "—",
            "roi_cls": ("pos" if (roi or 0) > 0 else "neg" if (roi or 0) < 0 else ""),
            "wl_str": f"{v.get('wins', 0)} / {v.get('losses', 0)}",
            "profit_str": f"${profit:+,.0f}" if profit is not None else "—",
            "profit_cls": ("pos" if (profit or 0) > 0 else "neg" if (profit or 0) < 0 else ""),
            "weight_str": f"{weight:.1%}" if weight else "—",
        })
    window_obj = scoreboard.get("window", {})
    window = f"{window_obj.get('start','—')} → {window_obj.get('end','—')}"
    content = env.get_template("sources.html").render(
        rows=rows,
        n_sources=len([r for r in rows if r["n_events"] > 0]),
        n_events=scoreboard.get("n_events", 0),
        window=window,
    )
    return _layout(env, "Source Scoreboard", "sources", content)


def render_methodology(env: Environment) -> str:
    content = env.get_template("methodology.html").render()
    return _layout(env, "Methodology", "methodology", content)


def render_backtest(env: Environment, scoreboard: dict) -> str:
    sources = scoreboard.get("sources", {})
    fc = sources.get("flashcat-blended", {})
    slices_raw = fc.get("slices", {}) or {}
    slice_rows = []
    for label, v in sorted(slices_raw.items()):
        wagered = v.get("wagered", 0.0)
        profit = v.get("profit", 0.0)
        wins = int(v.get("wins", 0))
        losses = int(v.get("losses", 0))
        n = wins + losses
        roi = v.get("roi")
        slice_rows.append({
            "label": label,
            "n": n,
            "wl": f"{wins} / {losses}",
            "wagered": wagered,
            "profit_str": f"${profit:+,.0f}",
            "profit_cls": "pos" if profit > 0 else "neg" if profit < 0 else "",
            "roi_str": f"{roi:+.1%}" if roi is not None else "—",
            "roi_cls": "pos" if (roi or 0) > 0 else "neg" if (roi or 0) < 0 else "",
        })
    overall_roi = fc.get("roi")
    overall_brier = fc.get("brier")
    overall_profit = fc.get("profit", 0.0)
    window_obj = scoreboard.get("window", {})
    window = f"{window_obj.get('start','—')} → {window_obj.get('end','—')}"
    # Render charts
    _bankroll_chart(scoreboard.get("bankroll_curve", []) or [], ASSETS_DIR / "bankroll.png")
    _calibration_chart(fc.get("calibration", []) or [], ASSETS_DIR / "calibration.png")
    content = env.get_template("backtest.html").render(
        window=window,
        n_events=fc.get("n_events", 0),
        overall_roi_str=f"{overall_roi:+.1%}" if overall_roi is not None else "—",
        overall_roi_cls="pos" if (overall_roi or 0) > 0 else "neg" if (overall_roi or 0) < 0 else "",
        overall_brier_str=f"{overall_brier:.4f}" if overall_brier is not None else "—",
        overall_profit_str=f"${overall_profit:+,.0f}",
        overall_profit_cls="pos" if overall_profit > 0 else "neg" if overall_profit < 0 else "",
        slice_rows=slice_rows,
    )
    return _layout(env, "Backtest", "backtest", content)


def write_source_scoreboard_md(scoreboard: dict, path: Path) -> None:
    sources = scoreboard.get("sources", {})
    lines = ["# Source Scoreboard\n"]
    window = scoreboard.get("window", {})
    lines.append(f"Window: **{window.get('start','—')} → {window.get('end','—')}** ({window.get('sport','—')})\n")
    lines.append(f"Events graded: **{scoreboard.get('n_events', 0)}**\n\n")
    lines.append("| Source | Events | Brier ↓ | ROI | Wins/Losses | Profit |\n")
    lines.append("|---|---:|---:|---:|---:|---:|\n")
    for src, v in sources.items():
        brier = v.get("brier")
        roi = v.get("roi")
        profit = v.get("profit")
        lines.append(
            f"| {src} | {v.get('n_events',0)} | "
            f"{brier:.4f}" if brier is not None else f"| {src} | {v.get('n_events',0)} | — "
        )
        # Simpler implementation: just rebuild line cleanly.
    # rebuild cleanly
    lines = ["# Source Scoreboard\n"]
    lines.append(f"Window: **{window.get('start','—')} → {window.get('end','—')}** ({window.get('sport','—')})\n\n")
    lines.append(f"Events graded: **{scoreboard.get('n_events', 0)}**\n\n")
    lines.append("| Source | Events | Brier ↓ | ROI | Wins/Losses | Profit |\n")
    lines.append("|---|---:|---:|---:|---:|---:|\n")
    for src, v in sources.items():
        brier = v.get("brier")
        roi = v.get("roi")
        profit = v.get("profit")
        brier_s = f"{brier:.4f}" if brier is not None else "—"
        roi_s = f"{roi:+.1%}" if roi is not None else "—"
        profit_s = f"${profit:+,.0f}" if profit is not None else "—"
        lines.append(
            f"| {src} | {v.get('n_events',0)} | {brier_s} | {roi_s} | "
            f"{v.get('wins',0)}/{v.get('losses',0)} | {profit_s} |\n"
        )
    path.write_text("".join(lines))


def build(events: list[Event] | None = None) -> None:
    ensure_dirs()
    _write_logos()
    weights = load_weights()
    if SOURCE_SCOREBOARD_PATH.exists():
        with open(SOURCE_SCOREBOARD_PATH) as f:
            scoreboard = json.load(f)
    else:
        scoreboard = {"sources": {}, "n_events": 0, "window": {}, "bankroll_curve": []}
    events = events or []
    env = _env()
    (DOCS_DIR / "index.html").write_text(render_index(env, events, weights))
    render_event_pages(env, events, weights)
    (DOCS_DIR / "source-scoreboard.html").write_text(render_sources(env, scoreboard, weights))
    (DOCS_DIR / "methodology.html").write_text(render_methodology(env))
    (DOCS_DIR / "backtest.html").write_text(render_backtest(env, scoreboard))
    write_source_scoreboard_md(scoreboard, DOCS_DIR / "source-scoreboard.md")
    log.info("Site built → %s", DOCS_DIR)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    build()
